name: Build Harvester Catalog Image and Publish on Release

on:
  workflow_dispatch:
  release:
    types: [published]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run tests
        uses: ./.github/actions/lint

  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check package version
        env:
          TAG_VERSION: ${{ github.event.release.tag_name }}
        run: |
          VERSION=$(jq -r .version package.json)
          EXTENSION_VERSION=$(jq -r .version pkg/harvester/package.json)
          PKG_VERSION="v${EXTENSION_VERSION}"

          if [[ "$VERSION" != "$EXTENSION_VERSION" ]]; then
            echo "Package version mismatch: $VERSION vs $EXTENSION_VERSION"
            exit 1
          fi

          if [[ "${TAG_VERSION}" != "$PKG_VERSION" ]]; then
            echo "Package version $PKG_VERSION in pkg/harvester/package.json does not match tag version ${TAG_VERSION}"
            exit 1
          fi
         
          echo "Package version and tag version match: ${TAG_VERSION}"

  build-and-push-extension-catalog:
    needs: 
      - lint
      - check-version
    uses: ./.github/workflows/build-extension-catalog.yml
    permissions:
      actions: write
      contents: read
      packages: write
      id-token: write
    with:
      registry_target: docker.io
      registry_user: rancher
    secrets: inherit
