name: Create Draft Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.5.1, v1.6.0-rc5

# on:
#   workflow_dispatch:
#     inputs:
#       version:
#         description: 'Release version (e.g. 1.6.0-rc5)'
#         required: true
#         type: string

jobs:
  create-draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install conventional-changelog-cli
        run: yarn add -D conventional-changelog-cli

      - name: Generate changelog
        run: npx conventional-changelog -p angular -i CHANGELOG.md -s -r 0

      - name: Add original authors
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
          echo "Content of CHANGELOG.md before script:"
          head -10 CHANGELOG.md
          echo "Running script..."
          node scripts/add-original-authors.js
          echo "Content of CHANGELOG.md after script:"
          head -10 CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: v${{ github.event.inputs.version }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: ${{ contains(github.event.inputs.version, '-rc') || contains(github.event.inputs.version, '-dev') }} 