name: "[PR Management] Auto Assign Reviewer & Assignee & PR label && Andy Lee123 & 456"

on:
  pull_request_target:
    types: [opened, ready_for_review]

# defaults:
#   run:
#     shell: bash
#     working-directory: ./

permissions:
  pull-requests: write

jobs:
  auto-assign-reviewer:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: rancher/gh-issue-mgr/auto-assign-action@main
        with:
          configuration-path: .github/auto-assign-config.yaml

  auto-assign-pr-label:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Set PR Label
        id: extract_pr_label
        run: |
          PR_LABEL=$(node ./scripts/extract-pr-label.js "${{ github.event.pull_request.title }}")
          echo "PR_LABEL=$PR_LABEL" >> $GITHUB_OUTPUT
          gh pr edit ${{ github.event.pull_request.number }} --repo ${{ github.repository }}  --add-label "$PR_LABEL"
      # - name: Set PR label
      #   run: |
      #     gh pr edit ${{ github.event.pull_request.number }} --repo ${{ github.repository }}  --add-label "${{ steps.extract_pr_label.outputs.script_result }}"
