name: "[PR Management] Auto Assign Reviewer & Assignee"

# on:
#   pull_request_target:
#     types: [opened, ready_for_review]

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'PR title'
        required: true
        type: string

defaults:
  run:
    shell: bash
    working-directory: ./

permissions:
  pull-requests: write

jobs:
  auto-assign-reviewer:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: rancher/gh-issue-mgr/auto-assign-action@main
        with:
          configuration-path: .github/auto-assign-config.yaml

  # auto-assign-pr-label:
  #   if: github.event.pull_request.draft == false
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Extract PR label
  #       id: extract_pr_label
  #       env:
  #         PR_TITLE: ${{ github.event.inputs.title }}
  #       run: node .github/workflows/scripts/extract-pr-label.js "${{ github.event.inputs.title }}"
  #     - name: Set PR label
  #       run: |
  #         gh pr edit ${{ github.event.pull_request.number }} --repo ${{ github.repository }}  --add-label "${{ steps.extract_pr_label.outputs.script_result }}"
